### ISSUE TITLE
Difference using cast?

### ISSUE THREAD

**Issue by josegus** [oza75/Laravel-Database-Jsonable#2]
What's the difference between using this package and the $cast attribute inside a model?

**Comment by oza75** [comment]
Good question! As far as I know, Laravel casts properties are a bit limited. if it is used to casts dates it works very well but if we advance a little we are limited while this package, with the power of laravel collections, allows you to do all operations you want on fields defined in  Jsonable property. For example, imagine that we have a Post model that has an action field. This action field contains all actions on the post, e.g: comments and likes.If we want to retrieve all the reactions on a post, we can easily do it using the sum method of laravel collections or another method.

I will close this issue but if you have any other questions do not hesitate to reopen it
